name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Xcode Setup
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.0.0'

      - name: Build the app
        run: |
          xcodebuild -scheme HabitTracker -sdk iphoneos -configuration Release -allowProvisioningUpdates

      - name: Run tests
        run: |
          xcodebuild test -scheme HabitTracker -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest'
