name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Xcode
        run: |
          xcode-select --install
          sudo xcode-select --switch /Library/Developer/CommandLineTools
          sudo xcodebuild -license accept

      #- name: Install dependencies
      #  run: |
      #    swift package update  # Update dependencies if using Swift Package Manager

      - name: Build the app
        run: |
          xcodebuild -scheme HabitTracker -sdk iphoneos -configuration Release

      - name: Run tests
        run: |
          xcodebuild test -scheme HabitTracker -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest'
